### PR TITLE
Fix CDK 6.1 issue with correct expected type

### LINKED ISSUE #115: CDK 6.1.0 compatibility issue?
Hi,

I tried upgrading CDK from 6.0.2 to 6.1.0 and am getting some error like this when I invoke the context menu:

this.origin.getBoundingClientRect is not a function

For now I'm sticking with 6.0.2 but just wanted to note this issue..not sure if the CDK is buggy or if this package needs updating. 

Regards,

-S. Arora

### PR DESCRIPTION
**Pull request by carlmon**
[This change to Material2](https://github.com/angular/material2/commit/04b076da83b41203edeca376a384ec9ce4694848) now checks for `instanceof ElementRef`.

My fix passes elements using this expected class which fixes #115. It works with CDK 6.0 as well as 6.1. Let me know if it should be fixed in another way.

### CODE REVIEW

**Comment by isaacplmann** [comment]
Thanks! On vacation until Thursday. I'll take a look then.

**Comment by isaacplmann** [comment]
Thanks!

**Comment by teterovic** [comment]
Can we expect this on npm soon ?

**Comment by isaacplmann** [comment]
Yep. Just published 5.0.1

**Comment by melodysummer** [comment]
5.0.1 cannot be founded on npm.
Could you check the version please?  @isaacplmann

**Comment by teterovic** [comment]
@melodysummer  
npm install ngx-contextmenu@5.0.1 --save

**Comment by melodysummer** [comment]
image

But it failed

**Comment by melodysummer** [comment]
@teterovic  what's your npm proxy or registry library, please.
I don't konw if it is related to this.
